### ISSUE TITLE
scroller in iframe

### ISSUE THREAD

**Issue by andriusvs** [dinbror/bpopup#44]
need autoscroller in iframe

**Comment by Joshdw** [comment]
Hey Andriusvs, I am pretty sure you can do this with the iframeAttr Option.

`iframeAttr [string] (‘scrolling=”no” frameborder=”0″‘)
Gives you the possibility to customize the built-in iframe support. Default removes the scrollbar and border. Version 0.9.4`

So a string of scrolling="yes" should allow scrollbars and autoscrolling. Not sure though, but good luck.

Edit: Also keep in mind the iframe source needs to be on the same domain or it will not be possible due to Same Origin Policy.

**Comment by dinbror** [comment]
Not a bpopup issue
